
import React from 'react';
import { KNOWLEDGE_BASE } from '../constants';

const KnowledgeBase: React.FC = () => {
  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <header>
        <h2 className="text-3xl font-bold text-gray-900">Voice DNA</h2>
        <p className="text-gray-500 mt-2">The guidelines that define Reagan's executive presence.</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <section className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm space-y-4">
          <h3 className="text-lg font-bold flex items-center gap-2">
            <span className="w-1.5 h-1.5 bg-black rounded-full" />
            Core Principles
          </h3>
          <pre className="whitespace-pre-wrap font-sans text-sm text-gray-600 leading-relaxed">
            {KNOWLEDGE_BASE.voice}
          </pre>
        </section>

        <section className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm space-y-4">
          <h3 className="text-lg font-bold flex items-center gap-2">
            <span className="w-1.5 h-1.5 bg-black rounded-full" />
            The Reagan Playbook
          </h3>
          <pre className="whitespace-pre-wrap font-sans text-sm text-gray-600 leading-relaxed">
            {KNOWLEDGE_BASE.playbook}
          </pre>
        </section>

        <section className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm col-span-1 md:col-span-2">
          <h3 className="text-lg font-bold flex items-center gap-2 mb-4">
            <span className="w-1.5 h-1.5 bg-black rounded-full" />
            Output Quality Check
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5 gap-4">
            {['Specificity', 'Impact Clarity', 'Tone Match', 'Forward Motion', 'Brevity'].map(item => (
              <div key={item} className="p-3 bg-gray-50 rounded-lg text-center border border-gray-100">
                <p className="text-xs font-bold text-gray-900">{item}</p>
                <p className="text-[10px] text-gray-400 uppercase mt-1">Scale 0-2</p>
              </div>
            ))}
          </div>
          <p className="text-xs text-gray-400 mt-4 text-center">Minimum ship score: 8/10. Any output generated by the engine is auto-vetted against these criteria.</p>
        </section>
      </div>
    </div>
  );
};

export default KnowledgeBase;
